### ISSUE TITLE
Failed to find yamllint executable: Expected exit code 0, but got 1

### ISSUE THREAD

**Issue by liry** [aesy/yamllint-intellij#5]
```
2022-10-26 09:04:29,928 [39449181]   WARN - #i.a.y.YamllintExecutableFinder - Failed to find yamllint executable: Expected exit code 0, but got 1
2022-10-26 09:04:29,928 [39449181]   INFO - #i.a.y.YamllintProjectAnalyzer - No yamllint executable found, defaulting to 'yamllint'
```
In terminal it works:
```
> which yamllint
/Users/.../.local/bin/yamllint
> echo $?
0
```
One thing that comes to my mind is access rights, but IDEA process runs under the same user as my terminal. The other one is customised PATH I have in terminal (`~/.profile`) but which is not in the IDEAs cmd line.

BTW, given the fact, that plugin settings are per-project, I need to manually set the executable in each project 😿

**Comment by aesy** [comment]
Hey, thanks for the report!

How are you running IDEA? It looks like you're on Windows based on the path. Do you use WSL?

> One thing that comes to my mind is access rights, but IDEA process runs under the same user as my terminal. The other one is customised PATH I have in terminal (~/.profile) but which is not in the IDEAs cmd line.

I'm thinking along the same lines. At what point is `.local/bin/` added to the PATH?

Just to rule out any other errors, can you enable and post the debug/fine logs?
To enable it, go to `Help > Diagnostic Tools > Debug Log Settings...` and add: `io.aesy.yamllint:all`. You probably also want to remove the `<component name="YamllintSettings">` section from the workspace file (usually `.idea/workspace.xml` when the project is closed in order to force the plugin to reinitialize when you open it again. You can then find the log file using `Help > Show Log in Explorer` (if you are on Windows).

> BTW, given the fact, that plugin settings are per-project, I need to manually set the executable in each project 😿

The reason for that is because folks may want to use different versions of yamllint in their projects. It shouldn't be that much of an issue as long as the auto-detect feature works.

**Comment by aesy** [comment]
I'll close this issue for now, feel free to reopen it if you have any new findings
